// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD27YupYctW6d6I7jA2FGdrXiCfc01M5w',
    appId: '1:48533562859:web:a76dc625585ad0cb5f65ae',
    messagingSenderId: '48533562859',
    projectId: 'employee-b4b7a',
    authDomain: 'employee-b4b7a.firebaseapp.com',
    storageBucket: 'employee-b4b7a.appspot.com',
    measurementId: 'G-BGHNV6VL9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3JPAM8rSzuUHZWiaRQXPrHMc94rqkZCU',
    appId: '1:48533562859:android:f7b50c37d87f3ca75f65ae',
    messagingSenderId: '48533562859',
    projectId: 'employee-b4b7a',
    storageBucket: 'employee-b4b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBKDTN_1_mq7cVMNT7KD4pzTlmb5Ntpwo',
    appId: '1:48533562859:ios:098541f71cc15fd05f65ae',
    messagingSenderId: '48533562859',
    projectId: 'employee-b4b7a',
    storageBucket: 'employee-b4b7a.appspot.com',
    iosClientId: '48533562859-p4lhqu75sq61oa4bjadrngcm16mtb8qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileEngineer',
  );
}
